# Generated by Django 5.1.15 on 2026-10-02 16:07

import apps.common.encryption
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_keys', '0003_apikeyauditlog_actor_label_apikeyauditlog_actor_user_and_more'),
        ('inbox', '0004_backfill_inboxreply_status'),
        ('social_accounts', '0021_flag_pinterest_missing_boards_write'),
        ('workspaces', '0003_alter_workspace_primary_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('id', models.CharField(editable=False, max_length=68, primary_key=True, serialize=False)),
                ('principal', models.CharField(db_index=True, max_length=200)),
                ('oauth_application_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('oauth_token_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('arguments', models.JSONField(default=dict)),
                ('callback_url', apps.common.encryption.EncryptedTextField()),
                ('callback_hash', models.CharField(db_index=True, max_length=64)),
                ('signing_secret', apps.common.encryption.EncryptedTextField()),
                ('previous_secret', apps.common.encryption.EncryptedTextField(blank=True, default='')),
                ('previous_secret_until', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('stopped_reason', models.CharField(blank=True, default='', max_length=40)),
                ('generation', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_keys.apikey')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_accounts.socialaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='EventOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation', models.UUIDField()),
                ('event_id', models.CharField(max_length=68)),
                ('payload', apps.common.encryption.EncryptedTextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inbox.inboxmessage')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='mcp_server.eventsubscription')),
            ],
        ),
        migrations.AddConstraint(
            model_name='eventsubscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('api_key__isnull', False), ('oauth_application_id__isnull', True), ('oauth_token_checksum', '')), models.Q(('api_key__isnull', True), ('oauth_application_id__isnull', False), models.Q(('oauth_token_checksum', ''), _negated=True)), _connector='OR'), name='mcp_subscription_credential_kind'),
        ),
        migrations.AddIndex(
            model_name='eventoutbox',
            index=models.Index(fields=['status', 'next_attempt_at'], name='mcp_outbox_due'),
        ),
        migrations.AddConstraint(
            model_name='eventoutbox',
            constraint=models.UniqueConstraint(fields=('subscription', 'event_id'), name='mcp_event_subscription_dedupe'),
        ),
    ]
