# Generated by Django 5.1.15 on 2026-10-07 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0015_conversation_read_state'),
        ('mcp_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoutbox',
            name='canonical_event_revision',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoutbox',
            name='canonical_generation',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoutbox',
            name='canonical_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inbox.conversationmessage'),
        ),
        migrations.AlterField(
            model_name='eventoutbox',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inbox.inboxmessage'),
        ),
        migrations.AddConstraint(
            model_name='eventoutbox',
            constraint=models.CheckConstraint(condition=models.Q(('message__isnull', False), ('canonical_message__isnull', False), _connector='OR'), name='mcp_event_message_required'),
        ),
    ]
