# Generated by Django 5.1.15 on 2026-10-03 10:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_backfill_inboxreply_status'),
        ('social_accounts', '0021_flag_pinterest_missing_boards_write'),
        ('workspaces', '0003_alter_workspace_primary_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=30)),
                ('platform_conversation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('peer_id', models.CharField(blank=True, default='', max_length=255)),
                ('peer_ambiguous', models.BooleanField(default=False)),
                ('identity_kind', models.CharField(choices=[('platform', 'Provider conversation'), ('verified_peer', 'Verified one-to-one peer')], max_length=20)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_conversations', to='social_accounts.socialaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_conversations', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'inbox_conversation',
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=30)),
                ('conversation_attribution', models.CharField(blank=True, choices=[('platform', 'Provider conversation'), ('verified_peer', 'Verified one-to-one peer')], default='', max_length=20)),
                ('platform_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('sender_id', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_id', models.CharField(blank=True, default='', max_length=255)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('delivery_status', models.CharField(choices=[('observed', 'Observed on provider'), ('provider_accepted', 'Accepted by provider'), ('delivery_unverified', 'Delivery unverified')], default='observed', max_length=25)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_message', to='inbox.inboxmessage')),
                ('legacy_reply', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_message', to='inbox.inboxreply')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_messages', to='social_accounts.socialaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_messages', to='workspaces.workspace')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='inbox.inboxconversation')),
            ],
            options={
                'db_table': 'inbox_conversation_message',
                'ordering': ['occurred_at', 'first_seen_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConversationSyncState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=30)),
                ('stream', models.CharField(choices=[('dm', 'Direct messages'), ('comment', 'Comments')], max_length=20)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='unknown', max_length=10)),
                ('coverage', models.CharField(choices=[('unknown', 'Unknown'), ('partial', 'Partial')], default='unknown', max_length=10)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_sync_states', to='social_accounts.socialaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_sync_states', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'inbox_conversation_sync_state',
                'constraints': [models.UniqueConstraint(fields=('social_account', 'platform', 'stream'), name='inbox_convo_sync_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='inboxconversation',
            index=models.Index(fields=['workspace', 'social_account', 'peer_id'], name='inbox_convo_scope_peer'),
        ),
        migrations.AddConstraint(
            model_name='inboxconversation',
            constraint=models.UniqueConstraint(fields=('social_account', 'platform', 'platform_conversation_id'), name='inbox_convo_provider_unique'),
        ),
        migrations.AddConstraint(
            model_name='inboxconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('platform_conversation_id__isnull', True), models.Q(('peer_id', ''), _negated=True)), fields=('social_account', 'platform', 'peer_id'), name='inbox_convo_fallback_unique'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['workspace', 'social_account', 'occurred_at'], name='inbox_convo_msg_scope_time'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['conversation', 'occurred_at'], name='inbox_convo_msg_thread_time'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['conversation', 'first_seen_at', 'id'], name='inbox_convo_msg_observed'),
        ),
        migrations.AddConstraint(
            model_name='conversationmessage',
            constraint=models.UniqueConstraint(fields=('social_account', 'platform', 'platform_message_id'), name='inbox_convo_msg_provider_unique'),
        ),
    ]
