# Generated by Django 5.1.15 on 2026-10-03 10:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0005_inboxconversation_conversationmessage_and_more'),
        ('social_accounts', '0021_flag_pinterest_missing_boards_write'),
        ('workspaces', '0003_alter_workspace_primary_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=30)),
                ('actor_scope', models.CharField(max_length=255)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('payload_fingerprint', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('expected_revision', models.PositiveBigIntegerField()),
                ('expected_generation', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('prepared', 'Prepared locally'), ('claimed', 'Claimed locally (dry run)'), ('confirmed', 'Explicitly reconciled'), ('failed', 'Explicitly known not sent'), ('outcome_unknown', 'Outcome unknown; reconciliation required'), ('superseded', 'Superseded before dispatch')], default='prepared', max_length=20)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('fencing_token', models.PositiveBigIntegerField(default=0)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('external_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('outcome_code', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_operations', to='inbox.inboxconversation')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_operations', to='social_accounts.socialaccount')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_send_operations', to='inbox.conversationmessage')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_operations', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'inbox_send_operation',
            },
        ),
        migrations.CreateModel(
            name='ConversationWorkState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation', models.PositiveBigIntegerField(default=0)),
                ('conversation_revision', models.PositiveBigIntegerField(default=0)),
                ('burst_started_at', models.DateTimeField(blank=True, null=True)),
                ('latest_incoming_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('owner_paused', models.BooleanField(default=False)),
                ('identity_quarantined', models.BooleanField(default=False)),
                ('ordering_uncertain', models.BooleanField(default=False)),
                ('history_gap', models.BooleanField(default=False)),
                ('pause_reason', models.CharField(blank=True, default='', max_length=40)),
                ('fencing_counter', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply_work_state', to='inbox.inboxconversation')),
                ('latest_incoming', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_reply_work_states', to='inbox.conversationmessage')),
                ('active_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_work_states', to='inbox.sendoperation')),
            ],
            options={
                'db_table': 'inbox_conversation_work_state',
            },
        ),
        migrations.AddConstraint(
            model_name='sendoperation',
            constraint=models.UniqueConstraint(fields=('conversation', 'actor_scope', 'idempotency_key'), name='inbox_send_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='sendoperation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['prepared', 'claimed', 'outcome_unknown'])), fields=('conversation',), name='inbox_send_single_active'),
        ),
        migrations.AddIndex(
            model_name='conversationworkstate',
            index=models.Index(fields=['owner_paused', 'due_at'], name='inbox_work_pause_due'),
        ),
    ]
