# Generated by Django 5.1.15 on 2026-10-04 04:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


def preserve_enrolled_history(apps, schema_editor):
    alias = schema_editor.connection.alias
    if apps.get_model('inbox', 'DMSendControl').objects.using(alias).exists():
        raise RuntimeError('Cannot reverse the DM send gate while enrolled controls or attempts exist. Preserve the safety history.')


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0006_reply_coordination'),
        ('social_accounts', '0021_flag_pinterest_missing_boards_write'),
        ('workspaces', '0003_alter_workspace_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxreply',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed'), ('unknown', 'Outcome unknown')], db_index=True, default='draft', max_length=10),
        ),
        migrations.CreateModel(
            name='DMSendControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=30)),
                ('account_platform_id', models.CharField(max_length=255)),
                ('paused', models.BooleanField(default=True)),
                ('epoch', models.PositiveBigIntegerField(default=1)),
                ('resume_cutoff', models.DateTimeField(blank=True, null=True)),
                ('coverage_from', models.DateTimeField()),
                ('coverage_version', models.CharField(max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dm_send_control', to='social_accounts.socialaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'inbox_dm_send_control',
            },
        ),
        migrations.CreateModel(
            name='DMSendAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epoch', models.PositiveBigIntegerField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('outcome', models.CharField(choices=[('unknown', 'Possibly in flight / outcome unknown'), ('sent', 'Provider accepted'), ('not_sent', 'Known not sent')], default='unknown', max_length=10)),
                ('reason_code', models.CharField(default='attempt_committed', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dm_send_attempts', to='inbox.inboxreply')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='inbox.dmsendcontrol')),
            ],
            options={
                'db_table': 'inbox_dm_send_attempt',
                'constraints': [models.UniqueConstraint(condition=models.Q(('outcome', 'unknown')), fields=('control',), name='inbox_dm_one_unresolved')],
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, preserve_enrolled_history),
    ]
