# Generated by Django 5.1.15 on 2026-10-05 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


def preserve_owned_history(apps, schema_editor):
    alias = schema_editor.connection.alias
    if (
        apps.get_model("inbox", "DMConversationOwnership").objects.using(alias).exists()
        or apps.get_model("inbox", "SendOperation").objects.using(alias).filter(
            models.Q(ownership__isnull=False) | models.Q(reply__isnull=False) | models.Q(attempt__isnull=False)
        ).exists()
        or apps.get_model("inbox", "DMSendAttempt").objects.using(alias).filter(operation__isnull=False).exists()
    ):
        raise RuntimeError("Cannot reverse V2 dispatch ownership while enrollment or delivery history exists.")


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0007_dm_send_gate'),
        ('social_accounts', '0021_flag_pinterest_missing_boards_write'),
        ('workspaces', '0003_alter_workspace_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmsendattempt',
            name='operation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='durable_attempt', to='inbox.sendoperation'),
        ),
        migrations.AddField(
            model_name='sendoperation',
            name='attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='send_operation', to='inbox.dmsendattempt'),
        ),
        migrations.AddField(
            model_name='sendoperation',
            name='owner_epoch',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sendoperation',
            name='reply',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='send_operation', to='inbox.inboxreply'),
        ),
        migrations.AddField(
            model_name='sendoperation',
            name='target_platform_message_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sendoperation',
            name='status',
            field=models.CharField(choices=[('prepared', 'Prepared locally'), ('claimed', 'Claimed locally'), ('confirmed', 'Provider accepted or explicitly reconciled'), ('failed', 'Explicitly known not sent'), ('outcome_unknown', 'Outcome unknown; reconciliation required'), ('superseded', 'Superseded before dispatch')], default='prepared', max_length=20),
        ),
        migrations.CreateModel(
            name='DMConversationOwnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=30)),
                ('account_platform_id', models.CharField(max_length=255)),
                ('platform_conversation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('peer_id', models.CharField(max_length=255)),
                ('identity_kind', models.CharField(max_length=20)),
                ('owner_scope', models.CharField(max_length=255)),
                ('epoch', models.PositiveBigIntegerField(default=1)),
                ('paused', models.BooleanField(default=True)),
                ('resume_cutoff', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_owners', to='inbox.dmsendcontrol')),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_ownership', to='inbox.inboxconversation')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='social_accounts.socialaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'inbox_dm_conversation_ownership',
            },
        ),
        migrations.AddField(
            model_name='sendoperation',
            name='ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='inbox.dmconversationownership'),
        ),
        migrations.AddConstraint(
            model_name='sendoperation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed'), models.Q(('target_platform_message_id', ''), _negated=True)), fields=('conversation', 'target_platform_message_id'), name='inbox_send_confirmed_target'),
        ),
        migrations.RunPython(migrations.RunPython.noop, preserve_owned_history),
    ]
