# Generated by Django 5.1.15 on 2026-10-05 07:19

from django.db import migrations, models


def preserve_owned_classification(apps, schema_editor):
    if apps.get_model('inbox', 'DMConversationOwnership').objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError('Cannot reverse conversation classification while persisted ownership exists. Keep safety metadata and compatible senders.')


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0008_dmsendattempt_operation_sendoperation_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='content_status',
            field=models.CharField(default='unknown', max_length=25),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='classification_reason',
            field=models.CharField(default='participants_missing', max_length=40),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='conversation_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('direct', 'Direct'), ('group', 'Group')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='inboxconversation',
            name='classification_reason',
            field=models.CharField(default='participants_missing', max_length=40),
        ),
        migrations.AddField(
            model_name='inboxconversation',
            name='conversation_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('direct', 'Direct'), ('group', 'Group')], default='unknown', max_length=10),
        ),
        migrations.RunPython(migrations.RunPython.noop, preserve_owned_classification),
    ]
