# Generated by Django 5.1.15 on 2026-10-07 10:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


def preserve_sync_evidence(apps, schema_editor):
    if any(apps.get_model("inbox", name).objects.using(schema_editor.connection.alias).exists()
           for name in ("InboxSyncConnection", "InboxSyncCheckpoint", "ConversationSyncIdentity",
                        "ConversationObservationState", "InboxSyncBudget")):
        raise RuntimeError("Durable sync evidence exists; preserve schema and disable workers for rollback.")


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0012_conversation_workflow'),
        ('social_accounts', '0022_socialaccount_analytics_auth_updated_at_and_more'),
        ('workspaces', '0003_alter_workspace_primary_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationObservationState',
            fields=[
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='observation_state', serialize=False, to='inbox.conversationmessage')),
                ('connection_generation', models.UUIDField()),
                ('content_fingerprint', models.CharField(max_length=64)),
                ('provider_updated_at', models.DateTimeField(blank=True, null=True)),
                ('provider_revision', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_observed_at', models.DateTimeField()),
                ('repair_required', models.BooleanField(default=False)),
                ('conflict_count', models.PositiveSmallIntegerField(default=0)),
                ('live_observed_at', models.DateTimeField(blank=True, null=True)),
                ('live_conversation_id', models.UUIDField(blank=True, null=True)),
                ('actionable_observed_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('retained_body', models.TextField(blank=True, default='')),
                ('retained_attachments', models.JSONField(blank=True, default=list)),
                ('retained_legacy_body', models.TextField(blank=True, default='')),
                ('retained_legacy_attachments', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inbox_conversation_observation',
            },
        ),
        migrations.CreateModel(
            name='InboxSyncBudget',
            fields=[
                ('app_key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('window_started_at', models.DateTimeField()),
                ('gets_reserved', models.PositiveSmallIntegerField(default=0)),
                ('account_spend', models.JSONField(default=dict)),
                ('active_leases', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inbox_sync_budget',
            },
        ),
        migrations.CreateModel(
            name='InboxSyncConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=30)),
                ('account_platform_id', models.CharField(max_length=255)),
                ('webhook_target_id', models.CharField(blank=True, default='', max_length=255)),
                ('generation', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('auth_fingerprint', models.CharField(max_length=64)),
                ('route_contract', models.CharField(default='meta-dm-v25-v1', max_length=40)),
                ('enabled', models.BooleanField(default=False)),
                ('ownership_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('bootstrap_baseline_at', models.DateTimeField(blank=True, null=True)),
                ('retry_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.CharField(blank=True, default='', max_length=40)),
                ('last_served_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='social_accounts.socialaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'inbox_sync_connection',
            },
        ),
        migrations.CreateModel(
            name='ConversationSyncIdentity',
            fields=[
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='sync_identity', serialize=False, to='inbox.inboxconversation')),
                ('connection_generation', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inbox.inboxsyncconnection')),
            ],
            options={
                'db_table': 'inbox_conversation_sync_identity',
            },
        ),
        migrations.CreateModel(
            name='InboxSyncCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_generation', models.UUIDField()),
                ('stream', models.CharField(choices=[('conversations', 'Conversations'), ('messages', 'Messages')], max_length=20)),
                ('scope_key', models.CharField(default='account', max_length=255)),
                ('context', models.CharField(choices=[('bootstrap', 'bootstrap'), ('backfill', 'backfill'), ('live', 'live'), ('repair', 'repair')], max_length=12)),
                ('scan_generation', models.PositiveBigIntegerField(default=1)),
                ('status', models.CharField(default='ready', max_length=12)),
                ('cursor', models.CharField(blank=True, default='', max_length=1024)),
                ('participant_ids', models.JSONField(blank=True, default=list)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('fence', models.PositiveBigIntegerField(default=0)),
                ('retry_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('restarts', models.PositiveSmallIntegerField(default=0)),
                ('pages_committed', models.PositiveIntegerField(default=0)),
                ('recent_cursor_digests', models.JSONField(blank=True, default=list)),
                ('last_page_digest', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=40)),
                ('scan_started_at', models.DateTimeField()),
                ('coverage_from', models.DateTimeField()),
                ('coverage', models.CharField(default='unknown', max_length=20)),
                ('last_committed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkpoints', to='inbox.inboxsyncconnection')),
            ],
            options={
                'db_table': 'inbox_sync_checkpoint',
                'indexes': [models.Index(fields=['status', 'retry_at'], name='inbox_sync_checkpoint_due')],
                'constraints': [models.UniqueConstraint(fields=('connection', 'stream', 'scope_key', 'context'), name='inbox_sync_checkpoint_unique')],
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, preserve_sync_evidence),
    ]
