# Generated by Django 5.1.15 on 2026-10-07 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


def preserve_receipts(apps, schema_editor):
    if apps.get_model("inbox", "InboxSyncReceipt").objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError("Sync delivery receipts exist; disable capture and preserve schema for rollback.")


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0015_conversation_read_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxSyncReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_generation', models.UUIDField()),
                ('event_key', models.CharField(max_length=64)),
                ('platform_message_id', models.CharField(max_length=255)),
                ('context', models.CharField(max_length=12)),
                ('kind', models.CharField(default='message', max_length=24)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('payload', models.JSONField(default=dict)),
                ('observed_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='inbox.inboxsyncconnection')),
            ],
            options={
                'db_table': 'inbox_sync_receipt',
                'indexes': [models.Index(fields=['status', 'updated_at'], name='inbox_sync_receipt_due')],
                'constraints': [models.UniqueConstraint(fields=('connection', 'connection_generation', 'event_key'), name='inbox_sync_receipt_dedupe')],
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, preserve_receipts),
    ]
