# Generated by Django 5.1.15 on 2026-10-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0017_native_reply_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxsynccheckpoint',
            name='content_fields_mode',
            field=models.CharField(default='extended', max_length=12),
        ),
        migrations.AddField(
            model_name='inboxsynccheckpoint',
            name='content_probe_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
