# Generated by Django 5.1.15 on 2026-10-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0022_platformpost_analytics_column_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformpost',
            name='analytics_availability',
            field=models.CharField(choices=[('unknown', 'Not yet verified'), ('available', 'Available'), ('inaccessible', 'Post unavailable'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_default='unknown', default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='platformpost',
            name='analytics_availability_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformpost',
            name='analytics_availability_source',
            field=models.CharField(blank=True, db_default='', default='', max_length=16),
        ),
        migrations.AddField(
            model_name='platformpost',
            name='analytics_error_category',
            field=models.CharField(blank=True, db_default='', default='', max_length=24),
        ),
        migrations.AddField(
            model_name='platformpost',
            name='analytics_error_evidence',
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
        migrations.AddField(
            model_name='platformpost',
            name='analytics_status_version',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
