"""MCP 2.0 event discovery, scoped subscriptions, and commit-safe inbox fanout.

No callbacks, grants, or secrets are generated by enabling this code. A client
must supply a verified destination and signing key in an authenticated request.
"""

from __future__ import annotations

import hashlib
import logging
import uuid
from datetime import timedelta
from typing import Any

from django.conf import settings
from django.db import transaction
from django.utils import timezone
from jsonschema import Draft202012Validator, FormatChecker, ValidationError

from apps.api_keys.models import ApiKey
from apps.inbox.models import InboxMessage
from apps.mcp.event_delivery import (
    CallbackError,
    canonical_json,
    validate_callback_url,
    validate_secret,
    verify_callback,
)
from apps.mcp.models import EventOutbox, EventSubscription
from apps.mcp.modern import MODERN_PROTOCOL_VERSION  # noqa: F401 - backward-compatible import
from apps.mcp.protocol import INVALID_PARAMS, METHOD_NOT_FOUND, JsonRpcError
from apps.members.models import WorkspaceMembership
from apps.social_accounts.models import SocialAccount

logger = logging.getLogger(__name__)
EVENT_NAME = "inbox.dm.received"
CALLBACK_ENDPOINT_ERROR = -32015
VERIFICATION_CACHE_SECONDS = 300
ROTATION_SECONDS = 300
MAX_TTL_SECONDS = 86400
EVENT_DEFINITION = {
    "name": EVENT_NAME,
    "description": "A new inbound direct message on one authorized social account. Fetch its authoritative contents with get_inbox_message; replies and self echoes never trigger this event.",
    "delivery": ["webhook"],
    "inputSchema": {
        "type": "object",
        "properties": {"social_account_id": {"type": "string", "format": "uuid"}},
        "required": ["social_account_id"],
        "additionalProperties": False,
    },
    "payloadSchema": {
        "type": "object",
        "properties": {
            "message_id": {"type": "string", "format": "uuid"},
            "workspace_id": {"type": "string", "format": "uuid"},
            "social_account_id": {"type": "string", "format": "uuid"},
        },
        "required": ["message_id", "workspace_id", "social_account_id"],
        "additionalProperties": False,
    },
}


def events_enabled():
    return bool(getattr(settings, "MCP_EVENTS_ENABLED", False))


def _require_enabled():
    if not events_enabled():
        raise JsonRpcError(METHOD_NOT_FOUND, "MCP Events are disabled")


def _permission(context):
    return bool(context["membership"].effective_permissions.get("use_inbox", False))


def _credential(context):
    """Capture a principal stable over OAuth refresh but isolated per client/workspace."""
    actor = context["api_key"]
    workspace = context["workspace"]
    if not actor.issued_by_id or not actor.issued_by.is_active or workspace.is_archived:
        raise JsonRpcError(INVALID_PARAMS, "Event access denied")
    base = {"owner_id": actor.issued_by_id, "workspace_id": workspace.pk}
    if getattr(actor, "is_oauth", False):
        from oauth2_provider.models import get_access_token_model

        request = context["request"]
        auth = request.META.get("HTTP_AUTHORIZATION", "")
        raw = auth.split(" ", 1)[1] if auth.lower().startswith("bearer ") else ""
        checksum = hashlib.sha256(raw.encode()).hexdigest()
        token = get_access_token_model().objects.filter(token_checksum=checksum, user_id=actor.issued_by_id).first()
        if not token or not token.application_id or not token.is_valid(["mcp"]):
            raise JsonRpcError(INVALID_PARAMS, "Event access denied")
        return {
            **base,
            "principal": f"oauth:{actor.issued_by_id}:{token.application_id}:{workspace.pk}",
            "api_key_id": None,
            "oauth_application_id": token.application_id,
            "oauth_token_checksum": checksum,
        }
    return {
        **base,
        "principal": f"key:{actor.pk}:{workspace.pk}",
        "api_key_id": actor.pk,
        "oauth_application_id": None,
        "oauth_token_checksum": "",
    }


def _authorized_account(context, arguments):
    if not _permission(context):
        raise JsonRpcError(INVALID_PARAMS, "Permission denied: use_inbox")
    account_id = arguments["social_account_id"]
    account = (
        context["api_key"]
        .social_accounts.all()
        .filter(
            pk=account_id,
            workspace_id=context["workspace"].pk,
            connection_status=SocialAccount.ConnectionStatus.CONNECTED,
        )
        .first()
    )
    if account is None:
        raise JsonRpcError(INVALID_PARAMS, "Social account not found or unavailable")
    return account


def _validate_params(params, method):
    """Validate lifecycle field types before permissions or network operations.

    maxAgeMs is typed but ignored for this emit-only event (cursor is null).
    Unknown fields fail closed instead of silently widening a subscription.
    """
    properties: dict[str, Any] = {"_meta": {"type": "object"}}
    if method == "list":
        properties["cursor"] = {"type": "string"}
        required = []
    else:
        properties.update(
            {
                "name": {"type": "string"},
                "arguments": EVENT_DEFINITION["inputSchema"],
                "delivery": {
                    "type": "object",
                    "properties": {
                        "mode": {"const": "webhook"},
                        "url": {"type": "string"},
                        "secret": {"type": "string"},
                    },
                    "required": ["mode", "url"] + (["secret"] if method == "subscribe" else []),
                    "additionalProperties": False,
                },
            }
        )
        required = ["name", "arguments", "delivery"]
        if method == "subscribe":
            properties.update(
                {
                    "cursor": {"type": ["string", "null"]},
                    "ttlMs": {"type": ["integer", "null"], "minimum": 1, "maximum": 9007199254740991},
                    "maxAgeMs": {"type": "integer", "minimum": 0, "maximum": 9007199254740991},
                }
            )
    try:
        Draft202012Validator(
            {
                "type": "object",
                "properties": properties,
                "required": required,
                "additionalProperties": False,
            },
            format_checker=FormatChecker(),
        ).validate(params)
    except ValidationError as exc:
        raise JsonRpcError(INVALID_PARAMS, "Invalid event parameters") from exc


def _identity_params(params, *, unsubscribing=False):
    if params.get("name") != EVENT_NAME:
        raise JsonRpcError(INVALID_PARAMS, "Unknown event")
    arguments = params.get("arguments")
    try:
        Draft202012Validator(EVENT_DEFINITION["inputSchema"], format_checker=FormatChecker()).validate(arguments)
    except ValidationError as exc:
        # Schema errors may contain client input; do not echo it (or secret fields).
        raise JsonRpcError(INVALID_PARAMS, "Invalid event arguments") from exc
    arguments = {"social_account_id": str(uuid.UUID(arguments["social_account_id"]))}
    delivery = params.get("delivery")
    if not isinstance(delivery, dict) or delivery.get("mode") != "webhook":
        raise JsonRpcError(INVALID_PARAMS, "Only webhook delivery is supported")
    try:
        url = validate_callback_url(delivery.get("url"), check_allowlist=not unsubscribing)
    except CallbackError as exc:
        raise JsonRpcError(CALLBACK_ENDPOINT_ERROR, "Callback endpoint rejected", {"reason": exc.reason}) from exc
    return arguments, delivery, url


def _subscription_id(principal, url, arguments):
    identity = canonical_json([principal, url, EVENT_NAME, arguments])
    return "sub_" + hashlib.sha256(identity).hexdigest()


def list_events(params, context):
    _require_enabled()
    _validate_params(params, "list")
    if params.get("cursor") is not None:
        raise JsonRpcError(INVALID_PARAMS, "Event catalog does not support pagination")
    credential = _credential(context)
    visible = (
        _permission(context)
        and context["api_key"]
        .social_accounts.all()
        .filter(workspace_id=credential["workspace_id"], connection_status="connected")
        .exists()
    )
    return {"events": [EVENT_DEFINITION] if visible else []}


def subscribe(params, context):
    _require_enabled()
    _validate_params(params, "subscribe")
    arguments, delivery, url = _identity_params(params)
    account = _authorized_account(context, arguments)
    credential = _credential(context)
    if params.get("cursor") is not None:
        raise JsonRpcError(INVALID_PARAMS, "This event does not support replay cursors")
    ttl = params.get(
        "ttlMs", min(getattr(settings, "MCP_EVENTS_SUBSCRIPTION_TTL_SECONDS", 86400), MAX_TTL_SECONDS) * 1000
    )
    # Null requests infinite life; this server only grants finite lifetimes.
    if ttl is None:
        ttl = MAX_TTL_SECONDS * 1000
    if isinstance(ttl, bool) or not isinstance(ttl, int) or ttl <= 0:
        raise JsonRpcError(INVALID_PARAMS, "ttlMs must be a positive integer or null")
    ttl = min(ttl, MAX_TTL_SECONDS * 1000)
    secret = delivery.get("secret")
    try:
        validate_secret(secret)
    except CallbackError as exc:
        raise JsonRpcError(INVALID_PARAMS, "Invalid webhook signing secret") from exc
    sub_id = _subscription_id(credential["principal"], url, arguments)
    now = timezone.now()
    # Persisted verification survives worker/restart; bounded to this principal,
    # callback and key. A replacement signing key always gets a fresh challenge.
    cached = (
        EventSubscription.objects.filter(
            principal=credential["principal"],
            callback_hash=hashlib.sha256(url.encode()).hexdigest(),
            active=True,
            expires_at__gt=now,
            verified_at__gt=now - timedelta(seconds=VERIFICATION_CACHE_SECONDS),
        )
        .order_by("-verified_at")
        .first()
    )
    if cached is None or cached.signing_secret != secret:
        try:
            verify_callback(url, secret, sub_id)
        except CallbackError as exc:
            raise JsonRpcError(CALLBACK_ENDPOINT_ERROR, "Callback verification failed", {"reason": exc.reason}) from exc
        verified_at = timezone.now()
    else:
        verified_at = cached.verified_at
    now = timezone.now()
    expires_at = now + timedelta(milliseconds=ttl)
    if credential["api_key_id"]:
        credential_expiry = (
            ApiKey.objects.filter(pk=credential["api_key_id"]).values_list("expires_at", flat=True).first()
        )
    else:
        from oauth2_provider.models import get_access_token_model

        credential_expiry = (
            get_access_token_model()
            .objects.filter(token_checksum=credential["oauth_token_checksum"])
            .values_list("expires", flat=True)
            .first()
        )
    if credential_expiry:
        expires_at = min(expires_at, credential_expiry)
    with transaction.atomic():
        subscription, created = EventSubscription.objects.select_for_update().get_or_create(
            pk=sub_id,
            defaults={
                **credential,
                "social_account": account,
                "name": EVENT_NAME,
                "arguments": arguments,
                "callback_url": url,
                "callback_hash": hashlib.sha256(url.encode()).hexdigest(),
                "signing_secret": secret,
                "expires_at": expires_at,
            },
        )
        if not created and subscription.signing_secret != secret:
            subscription.previous_secret = subscription.signing_secret
            subscription.previous_secret_until = now + timedelta(seconds=ROTATION_SECONDS)
        if not created and (not subscription.active or subscription.expires_at <= now):
            subscription.generation = uuid.uuid4()
            subscription.started_at = now
            subscription.deliveries.filter(status=EventOutbox.Status.PENDING).update(
                status=EventOutbox.Status.CANCELLED, last_error="subscription_restarted"
            )
        for key, value in credential.items():
            setattr(subscription, key, value)
        subscription.signing_secret = secret
        subscription.verified_at = verified_at
        subscription.expires_at = expires_at
        subscription.active = True
        subscription.stopped_reason = ""
        # Recheck against DB after verification's network call, before granting.
        if not subscription_authorized(subscription):
            raise JsonRpcError(INVALID_PARAMS, "Event access denied")
        subscription.save()
    return {"id": sub_id, "refreshBefore": _iso(subscription.expires_at), "cursor": None, "truncated": False}


def unsubscribe(params, context):
    _validate_params(params, "unsubscribe")
    arguments, _delivery, url = _identity_params(params, unsubscribing=True)
    credential = _credential(context)
    # Cancellation remains available after an OAuth user's selected workspace
    # changes. The immutable owner + client/key identity is still mandatory;
    # canonical account arguments and callback select the originally owned sub.
    matching = EventSubscription.objects.filter(
        owner_id=credential["owner_id"],
        name=EVENT_NAME,
        arguments=arguments,
        callback_hash=hashlib.sha256(url.encode()).hexdigest(),
        api_key_id=credential["api_key_id"],
    )
    if credential["api_key_id"]:
        matching = matching.filter(workspace_id=credential["workspace_id"])
    else:
        matching = matching.filter(oauth_application_id=credential["oauth_application_id"])
    with transaction.atomic():
        for sub in matching.select_for_update().order_by("pk"):
            if sub.callback_url == url:
                _stop(sub, "unsubscribed")
    return {}


def _stop(subscription, reason):
    subscription.active = False
    subscription.stopped_reason = reason
    subscription.signing_secret = ""
    subscription.previous_secret = ""
    subscription.previous_secret_until = None
    subscription.save(
        update_fields=[
            "active",
            "stopped_reason",
            "signing_secret",
            "previous_secret",
            "previous_secret_until",
            "updated_at",
        ]
    )
    subscription.deliveries.filter(status=EventOutbox.Status.PENDING).update(
        status=EventOutbox.Status.CANCELLED, last_error=reason
    )


def subscription_authorized(sub):
    """Re-read credential, user, account, workspace, membership on every attempt."""
    membership = (
        WorkspaceMembership.objects.select_related("user", "workspace", "custom_role")
        .filter(
            user_id=sub.owner_id,
            workspace_id=sub.workspace_id,
            user__is_active=True,
            workspace__is_archived=False,
        )
        .first()
    )
    if not membership or not membership.effective_permissions.get("use_inbox", False):
        return False
    if not SocialAccount.objects.filter(
        pk=sub.social_account_id, workspace_id=sub.workspace_id, connection_status="connected"
    ).exists():
        return False
    if sub.api_key_id:
        key = ApiKey.objects.filter(pk=sub.api_key_id, issued_by_id=sub.owner_id, workspace_id=sub.workspace_id).first()
        return bool(
            key
            and key.is_active
            and "use_inbox" in (key.permissions or [])
            and key.social_accounts.filter(pk=sub.social_account_id).exists()
        )
    from oauth2_provider.models import get_access_token_model

    token = (
        get_access_token_model()
        .objects.filter(
            token_checksum=sub.oauth_token_checksum,
            user_id=sub.owner_id,
            application_id=sub.oauth_application_id,
        )
        .first()
    )
    return bool(token and token.is_valid(["mcp"]))


def _iso(value):
    return value.isoformat().replace("+00:00", "Z")


def enqueue_inbox_event(message):
    """Create outbox rows in the inbox write's transaction; never send on commit.

    Ingestion calls only for newly inserted inbound messages, before leaving its
    atomic block. This function adds deduplication and a conservative echo guard.
    """
    if not events_enabled() or message.message_type != InboxMessage.MessageType.DM:
        return
    extra = message.extra if isinstance(message.extra, dict) else {}
    if extra.get("is_echo") or extra.get("is_self") or extra.get("direction") == "outbound":
        return
    now = timezone.now()
    if timezone.is_naive(message.received_at) or message.received_at > now + timedelta(minutes=5):
        # Never guess the original event timezone; ingestion must normalize it.
        return
    payload = canonical_json(
        {
            "eventId": "evt_" + message.pk.hex,
            "name": EVENT_NAME,
            "timestamp": _iso(message.received_at),
            "data": {
                "message_id": str(message.pk),
                "workspace_id": str(message.workspace_id),
                "social_account_id": str(message.social_account_id),
            },
            "cursor": None,
        }
    ).decode()
    ids = []
    with transaction.atomic():
        subscriptions = EventSubscription.objects.filter(
            active=True,
            expires_at__gt=now,
            workspace_id=message.workspace_id,
            social_account_id=message.social_account_id,
            name=EVENT_NAME,
            started_at__lte=message.received_at,
        )
        for subscription in subscriptions.iterator():
            if not subscription_authorized(subscription):
                continue
            delivery, created = EventOutbox.objects.get_or_create(
                subscription=subscription,
                event_id="evt_" + message.pk.hex,
                defaults={"message": message, "generation": subscription.generation, "payload": payload},
            )
            if created:
                ids.append(str(delivery.pk))
        if ids:
            transaction.on_commit(lambda: _queue_outbox(ids), robust=True)


def _queue_outbox(ids):
    from apps.mcp.tasks import deliver_event

    for delivery_id in ids:
        try:
            deliver_event(delivery_id)
        except Exception:
            # Persisted rows remain discoverable by the recurring recovery sweep.
            logger.error("Could not schedule MCP outbox row %s", delivery_id)
