# Generated by Django 5.1.15 on 2026-10-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0021_flag_pinterest_missing_boards_write'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='analytics_auth_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='analytics_reconnect_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='analytics_reconnect_context',
            field=models.CharField(blank=True, db_default='', default='', max_length=16),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='analytics_reconnect_evidence',
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='analytics_reconnect_reason',
            field=models.CharField(blank=True, db_default='', default='', max_length=24),
        ),
    ]
